# general project configurations
language: objective-c
osx_image: xcode10.1
xcode_workspace: TravisSetUpDemo.xcworkspace
xcode_scheme: DummyTarget
xcode_sdk: iphonesimulator11.0
warnings_are_errors: false
notifications:
  email:
    - rahul.kumar@airfi.aero
branches:
  only:
  - master
#cache: cocoapods
  
before_install:
# configurations for installing and updating cocoapods, xcpretty and swiftlint
  - pod repo update
  - gem install xcpretty
  - gem install xcpretty-json-formatter
  - pip install --user codecov

script:
  # script to build and run unit tests and UI tests
  - set -o pipefail && xcodebuild
    -workspace TravisSetUpDemo.xcworkspace
    -scheme DummyTarget
    -destination 'platform=iOS Simulator,name=iPhone 5s,OS=12.1'
    test |
    xcpretty
    

# script to upload code coverage to codecov
after_script: bash <(curl -s https://codecov.io/bash) -t 6a1be175-09fc-4b0b-b303-1c687b02664f

after_success:
  - codecov --file coverage/lcov.info --disable search    