# general project configurations
language: objective-c
osx_image: xcode10.1
xcode_workspace: TravisSetUpDemo.xcworkspace
xcode_scheme: TravisSetUpDemo
xcode_sdk: iphonesimulator11.0
warnings_are_errors: false
cache:
  - cocoapods
  
before_install:
# configurations for installing and updating cocoapods, xcpretty and swiftlint
  - pod repo update
  - gem install xcpretty
  - gem install xcpretty-json-formatter
  - gem install fastlane --no-ri --no-rdoc --no-document  

jobs:
  include:
    - stage: Unit Tests
      script:
        - fastlane scan -s TravisSetUpDemo