# general project configurations
language: objective-c
osx_image: xcode10.1
xcode_workspace: TravisSetUpDemo.xcworkspace
xcode_scheme: DummyTarget
xcode_sdk: iphonesimulator11.0
warnings_are_errors: false
#cache: cocoapods
  
before_install:
# configurations for installing and updating cocoapods, xcpretty and swiftlint
  - pod repo update
  - gem install xcpretty
  - gem install xcpretty-json-formatter

script:
  # script to build and run unit tests and UI tests
  - set -o pipefail && xcodebuild
    -workspace TravisSetUpDemo.xcworkspace
    -scheme DummyTarget
    -destination 'platform=iOS Simulator,name=iPhone 5s,OS=12.1'
    test |
    xcpretty